import os
import pytest
import numpy as np
import brainload as bl
import brainload.meshexport as me

THIS_DIR = os.path.dirname(os.path.abspath(__file__))
TEST_DATA_DIR = os.path.join(THIS_DIR, os.pardir, 'test_data')

# Respect the environment variable BRAINLOAD_TEST_DATA_DIR if it is set. If not, fall back to default.
TEST_DATA_DIR = os.getenv('BRAINLOAD_TEST_DATA_DIR', TEST_DATA_DIR)


def test_ply_header_no_color():
    header = me.ply_header(100, 150)
    expected_header = """ply
format ascii 1.0
comment Generated by Brainload
element vertex 100
property float x
property float y
property float z
element face 150
property list uchar int vertex_indices
end_header
"""
    assert header == expected_header


def test_ply_header_color():
    header = me.ply_header(100, 150, use_vertex_colors=True)
    expected_header = """ply
format ascii 1.0
comment Generated by Brainload
element vertex 100
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
property uchar alpha
element face 150
property list uchar int vertex_indices
end_header
"""
    assert header == expected_header


def test_ply_verts_no_color():
    verts = np.array([[1.5, 1.5, 1.5], [2.5, 2.5, 2.5], [3.5, 3.5, 3.5]])
    vert_rep = me.ply_verts(verts)
    expected = "1.500000 1.500000 1.500000\n2.500000 2.500000 2.500000\n3.500000 3.500000 3.500000\n"
    assert vert_rep == expected


def test_ply_verts_color():
    verts = np.array([[1.5, 1.5, 1.5], [2.5, 2.5, 2.5], [3.5, 3.5, 3.5]])
    colors = np.array([[255, 0, 0, 255], [0, 255, 0, 255], [0, 0, 255, 255]])
    vert_rep = me.ply_verts(verts, vertex_colors=colors)
    expected = "1.500000 1.500000 1.500000 255 0 0 255\n2.500000 2.500000 2.500000 0 255 0 255\n3.500000 3.500000 3.500000 0 0 255 255\n"
    assert vert_rep == expected


def test_ply_faces():
    faces = np.array([[0, 1, 2], [2, 3, 4], [4, 5, 6]])
    face_rep = me.ply_faces(faces)
    expected = "3 0 1 2\n3 2 3 4\n3 4 5 6\n"
    assert face_rep == expected


def test_mesh_to_ply_with_vcolors():
    verts = np.array([[1.5, 1.5, 1.5], [2.5, 2.5, 2.5], [3.5, 3.5, 3.5]])
    faces = np.array([[0, 1, 2], [2, 3, 4], [4, 5, 6]])
    colors = np.array([[255, 0, 0, 255], [0, 255, 0, 255], [0, 0, 255, 255]])
    ply = me.mesh_to_ply(verts, faces, vertex_colors=colors)
    expected = """ply
format ascii 1.0
comment Generated by Brainload
element vertex 3
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
property uchar alpha
element face 3
property list uchar int vertex_indices
end_header
1.500000 1.500000 1.500000 255 0 0 255
2.500000 2.500000 2.500000 0 255 0 255
3.500000 3.500000 3.500000 0 0 255 255
3 0 1 2
3 2 3 4
3 4 5 6
"""
    assert ply == expected

def test_mesh_to_ply_no_vcolors():
    verts = np.array([[1.5, 1.5, 1.5], [2.5, 2.5, 2.5], [3.5, 3.5, 3.5]])
    faces = np.array([[0, 1, 2], [2, 3, 4], [4, 5, 6]])
    ply = me.mesh_to_ply(verts, faces)
    expected = """ply
format ascii 1.0
comment Generated by Brainload
element vertex 3
property float x
property float y
property float z
element face 3
property list uchar int vertex_indices
end_header
1.500000 1.500000 1.500000
2.500000 2.500000 2.500000
3.500000 3.500000 3.500000
3 0 1 2
3 2 3 4
3 4 5 6
"""
    assert ply == expected
