"""
Functions for exporting meshes.

Functions for exporting brain meshes to formats used by common 3D modeling software.
"""

import os
import sys


#ply
#format ascii 1.0
#comment VCGLIB generated
#element vertex 3
#property float x
#property float y
#property float z
#property uchar red
#property uchar green
#property uchar blue
#property uchar alpha
#element face 1
#property list uchar int vertex_indices
#end_header
#0.0 0.0 0.0 0 0 255 255
#100.0 0.0 0.0 0 0 255 255
#200.0 200.0 0.0 0 0 255 255
#3 0 1 2

def mesh_to_ply(vertex_coords, faces, vertex_colors=None):
    """
    Write a PLY format string of a mesh.

    Write a PLY format string of a mesh. See http://paulbourke.net/dataformats/ply/ for details on the format.
    """
    use_vertex_colors = vertex_colors is not None
    num_vertices = vertex_coords.shape[0]
    num_faces = faces.shape[0]
    hdr = ply_header(num_vertices, num_faces, use_vertex_colors)
    verts = ply_verts(vertex_coords, vertex_colors)
    faces = ply_faces(faces, face_colors)
    return ''.join([hdr, verts, faces])


def ply_header(num_vertices, num_faces, use_vertex_colors):
    hdr_top = """
    ply
    format ascii 1.0
    comment Generated by Brainload
    """

    hdr_verts = """
    element vertex %d
    property float x
    property float y
    property float z
    """ % num_vertices

    hdr_vertex_colors = """
    property uchar red
    property uchar green
    property uchar blue
    property uchar alpha
    """

    hdr_face = """
    element face %d
    property list uchar int vertex_indices
    """ % num_faces

    hdr_end = """
    end_header
    """
    if use_vertex_colors:
        hdr_elements = [hdr_top, hdr_verts, hdr_vertex_colors, hdr_face, hdr_end]
    else:
        hdr_elements = [hdr_top, hdr_verts, hdr_face, hdr_end]
    return ''.join(hdr_elements)
